name: Dev build
on:
  push:
    branches:
      - master
      - dev
      - test*
      - feature*
  pull_request:
    branches:
      - master
      - dev
jobs:
  run-build:
    name: 测试构建
    runs-on: ubuntu-latest
    steps:
    - name: 下载jdk环境
      uses: actions/setup-java@v3
      with: 
        java-version: 8
        cache: 'gradle'
        distribution: 'temurin'
    - name: 获取github仓库下文件
      uses: actions/checkout@v3.5.3
    - name: 构建
      run: |
        sh ./gradlew build -Dfile.encoding=UTF-8 --info --no-daemon
    - name: 上传构建
      uses: actions/upload-artifact@v3.1.2
      with:
        path: build/libs
