on:
  push:
    branches:
      - master
      - test*
      - feature*
  pull_request:
    branches:
      - master
jobs:
  run-build:
    name: 测试构建
    runs-on: ubuntu-latest
    steps:
    - name: 下载jdk环境
      uses: actions/setup-java@v1.4.4
      with: 
        java-version: 8
